language: c
git:
  depth: false
  quiet: true
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-wheel
      - clang-format-5.0
before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py

install:
  - arduino --install-library "AdafruitIO"
  - arduino --install-library "WiFi101OTA"
  - arduino --install-library "WiFi101"
  - arduino --install-library "Adafruit_BME680"
script:
  - python run-clang-format.py -r .
  - arduino --verify --board arduino:samd:arduino_zero_native $PWD/mqttBME680/mqttBME680.ino
